# 第1章 評価履歴 | recsys-python

https://recsyslab.github.io/recsys-python/ja/chap01.html

## 準備

次のコードを書きなさい。

In [1]:
import numpy as np

# 評価履歴

次の行列$D_u$はユーザ$u$の評価履歴である。

$$
D_u = \begin{bmatrix}
  5 & 3 & 1 \\
  6 & 2 & 1 \\
  4 & 1 & 1 \\
  8 & 5 & -1 \\
  2 & 4 & -1 \\
  3 & 6 & -1 \\
  7 & 6 & -1 \\
  4 & 2 & ? \\
  5 & 1 & ? \\
  8 & 6 & ? \\
  3 & 4 & ? \\
  4 & 7 & ? \\
  4 & 4 & ? \\
\end{bmatrix}

$$

## 01 評価履歴の生成

評価履歴$D_u$を`ndarray`として生成するコードを書きなさい。得られた`ndarray`を$D_u$とすること。

In [2]:
Du = np.array([
  [5, 3, 1],
  [6, 2, 1],
  [4, 1, 1],
  [8, 5, -1],
  [2, 4, -1],
  [3, 6, -1],
  [7, 6, -1],
  [4, 2, np.nan],
  [5, 1, np.nan],
  [8, 6, np.nan],
  [3, 4, np.nan],
  [4, 7, np.nan],
  [4, 4, np.nan]
])

print('Du = \n{}'.format(Du))

Du = 
[[ 5.  3.  1.]
 [ 6.  2.  1.]
 [ 4.  1.  1.]
 [ 8.  5. -1.]
 [ 2.  4. -1.]
 [ 3.  6. -1.]
 [ 7.  6. -1.]
 [ 4.  2. nan]
 [ 5.  1. nan]
 [ 8.  6. nan]
 [ 3.  4. nan]
 [ 4.  7. nan]
 [ 4.  4. nan]]


## 02 評価履歴の形状

`Du`の形状を取得するコードを書きなさい。

In [3]:
print('Duの形状 = {}'.format(Du.shape))

Duの形状 = (13, 3)


## 03 評価履歴の行数

`Du`の行数を取得するコードを書きなさい。

In [4]:
print('Duの行数 = {}'.format(Du.shape[0]))

Duの行数 = 13


## 04 評価履歴の列数

`Du`の列数を取得するコードを書きなさい。

In [5]:
print('Duの列数 = {}'.format(Du.shape[1]))

Duの列数 = 3


## 05 評価履歴の全要素数

`Du`の全要素数を取得するコードを書きなさい。ただし、欠損値も含む。

In [6]:
print('Duの全要素数 = {}'.format(Du.size))

Duの全要素数 = 39


# アイテム

評価履歴$D_u$の$i$行目はアイテム$i∈I$に関するデータを表す。ここで、評価履歴$D_u$に含まれるアイテム集合は$I={0,1,…,12}$となる。$D_u$の$i$行目の1列目と2列目はアイテム$i$の特徴ベクトル$x_i$に対応する。このとき、次の問いに答えなさい。

## 06 アイテム集合
`Du`の各行のインデックス`i`は各アイテム $i$ のアイテムID $i$ に対応する。`Du`からアイテム集合$I$（アイテムIDを要素としたベクトル）を`ndarray`として生成するコードを書きなさい。得られた`ndarray`を`I`とすること。

In [7]:
'''
i = Du.shape[0]
I = np.array([i for i in range(i)])
'''
I = np.arange(Du.shape[0])
print('I = {}'.format(I))

I = [ 0  1  2  3  4  5  6  7  8  9 10 11 12]


## 07 アイテムの特徴ベクトルの集合

`Du`からアイテムの特徴ベクトルの集合（各アイテムの特徴ベクトル$x_i$を縦に結合した行列）を`ndarray`として生成するコードを書きなさい。得られた`ndarray`を`x`とすること。

In [8]:
# x = np.array([i[:2] for i in Du])
x = Du[:, :-1]

print('x = \n{}'.format(x))

x = 
[[5. 3.]
 [6. 2.]
 [4. 1.]
 [8. 5.]
 [2. 4.]
 [3. 6.]
 [7. 6.]
 [4. 2.]
 [5. 1.]
 [8. 6.]
 [3. 4.]
 [4. 7.]
 [4. 4.]]


## 08 アイテムiの特徴ベクトル

`x`からアイテム$i$の特徴ベクトル$x_i$を取得するコードを書きなさい。

In [9]:
i = 0
print('x{} = {}'.format(i, x[i]))

x0 = [5. 3.]


## 評価値

評価履歴$D_u$の$i$行目3列目はユーザ$u$のアイテム$i$に対する評価値$r_{u,i}$に対応する。$r_{u,i}=+1$は「好き」を、$r_{u,i}=−1$は「嫌い」を表す。ただし、?はユーザ$u$が未評価、すなわち欠損値であることを示す。このとき、次の問いに答えなさい。

## 09 評価値集合

`Du`から評価値集合（各評価値$r_{u,i}$を要素としたベクトル）を`ndarray`として生成するコードを書きなさい。得られた`ndarray`を`ru`とすること。

In [10]:
# ru = np.array([i[-1] for i in Du])
ru = Du[:, -1]

print('ru = {}'.format(ru))

ru = [ 1.  1.  1. -1. -1. -1. -1. nan nan nan nan nan nan]


## 10 評価値集合の形状

`ru`の形状を取得するコードを書きなさい。

In [11]:
print('ruの形状 = {}'.format(ru.shape))

ruの形状 = (13,)


## 11 評価値集合の全要素数

`ru`の全要素数を取得するコードを書きなさい。ただし、欠損値も含む。

In [12]:
print('ruの全要素数 = {}'.format(ru.size))

print('ruの全要素数 = {}'.format(ru.shape[0]))


ruの全要素数 = 13
ruの全要素数 = 13


## 12 評価値集合の部分集合

`ru`の`i`番目から`j-1`番目までの評価値集合を取得するコードを書きなさい。

In [13]:
i = 2
j = 5
print('ru{}からru{}までの評価値 = {}'.format(i, j-1, ru[i:j]))

ru2からru4までの評価値 = [ 1. -1. -1.]


## 13 評価値集合の要素の逆順

`ru`の要素を逆順に取得するコードを書きなさい。

In [14]:
print('ruの逆順 = {}'.format(ru[::-1]))

ruの逆順 = [nan nan nan nan nan nan -1. -1. -1. -1.  1.  1.  1.]


## 14 アイテムiに対する評価値

`ru`からアイテム$i$に対する評価値$r_{u,i}$を取得するコードを書きなさい。

In [15]:
i = 0
print('ru{} = {}'.format(i, ru[i]))

ru0 = 1.0


# アイテム集合

アイテム集合$I$のうちユーザ$u$が評価済みのアイテム集合を$I_u⊆I$と表す。このうち、ユーザ$u$が「好き」と評価したアイテム集合を$I^+_u⊆I$（$r_{u,i}=+1$を満たすアイテム集合）、ユーザ$u$が「嫌い」と評価したアイテム集合を$I^−_u⊆I$（$r_{u,i}=−1$を満たすアイテム集合）と表す。また、ユーザ$u$が未評価のアイテム集合は$\overline{I}_u=I∖I_u$と表される。ここで、$I∖I_u$は$I$から$I_u$を引いた差集合を表す。このとき、次の問いに答えなさい。

## 15 ユーザuが未評価であるか否かの判定

`ru`において、欠損値の要素には`True`を、それ以外の要素には`False`を入れたブール値配列を生成するコードを書きなさい。

In [16]:
print('ユーザuが未評価 = {}'.format(np.isnan(ru)))

ユーザuが未評価 = [False False False False False False False  True  True  True  True  True
  True]


## 16 ユーザが評価済みであるか否かの判定

`ru`において、欠損値の要素には`False`を、それ以外の要素には`True`を入れたブール値配列を生成するコードを書きなさい。

> `~`演算子は`~x`に対して`-(x+1)`

In [17]:
print('ユーザuが評価済み = {}'.format(~np.isnan(ru)))

ユーザuが評価済み = [ True  True  True  True  True  True  True False False False False False
 False]


## 17 ユーザuが評価済みのアイテム集合

`I`からユーザ$u$が評価済みのアイテム集合$I_u$を`ndarray`として生成するコードを書きなさい。得られた`ndarray`を`Iu`とすること。

In [18]:
Iu = I[~np.isnan(ru)]

print('Iu = {}'.format(Iu))

Iu = [0 1 2 3 4 5 6]


## 18 ユーザuが「好き」と評価したアイテム集合

`I`からユーザ$u$が「好き」と評価したアイテム集合$I_{u}^{+}$を`ndarray`として生成するコードを書きなさい。得られた`ndarray`を`Iup`とすること。

In [19]:
Iup = I[ru == +1]

print('Iu+ = {}'.format(Iup))

Iu+ = [0 1 2]


## 19 ユーザuが「嫌い」と評価したアイテム集合
`I`からユーザ$u$が「嫌い」と評価したアイテム集合$I_{u}^{-}$を`ndarray`として生成するコードを書きなさい。得られた`ndarray`を`Iun`とすること。

In [20]:
Iun = I[ru == -1]

print('Iu- = {}'.format(Iun))

Iu- = [3 4 5 6]


## 20 ユーザuが未評価のアイテム集合

`I`からユーザ$u$が未評価のアイテム集合$\overline{I}_{u}$を`ndarray`として生成するコードを書きなさい。得られた`ndarray`を`Iu_not`とすること。

In [21]:
Iu_not = np.setdiff1d(I, Iu)

print('Iu_not = {}'.format(Iu_not))

Iu_not = [ 7  8  9 10 11 12]


# 訓練データと予測対象データ

評価履歴$D_{u}$からユーザ$u$の訓練データ$D_{u}^{L}$を作成すると、次のとおりとなる。

$$
D_{u}^{L} = \left[
 \begin{array}{rrr}
  5 & 3 & +1 \\
  6 & 2 & +1 \\
  4 & 1 & +1 \\
  8 & 5 & -1 \\
  2 & 4 & -1 \\
  3 & 6 & -1 \\
  7 & 6 & -1 \\
 \end{array}
\right]
$$

ここで、訓練データ$D_{u}^{L}$に含まれる事例数は$\mid D_{u}^{L} \mid = 7$となる。また、訓練データ$D_{u}^{L}$のうち「好き」と評価された事例集合（正事例集合）を$D_{u}^{L+}$、「嫌い」と評価された事例集合（負事例集合）を$D_{u}^{L-}$と表す。それぞれの事例数は$\mid D_{u}^{L+} \mid = 3$、$\mid D_{u}^{L-} \mid = 4$となる。同様に、ユーザ$u$向けの予測対象データ$D_{u}^{U}$は次のとおりとなる。

$$
D_{u}^{U} = \left[
 \begin{array}{rrr}
  4 & 2 &  ? \\
  5 & 1 &  ? \\
  8 & 6 &  ? \\
  3 & 4 &  ? \\
  4 & 7 &  ? \\
  4 & 4 &  ? \\
 \end{array}
\right]
$$

ここで、予測対象データ$D_{u}^{U}$に含まれる事例数は$\mid D_{u}^{U} \mid = 6$となる。このとき、次の問いに答えなさい。

## 21 訓練データ
`D`uから訓練データ$D_{u}^{L}$を`ndarray`として生成するコードを書きなさい。得られた`ndarray`を`DuL`とすること。

In [22]:
DuL = Du[Iu]
print('DuL = \n{}'.format(DuL))

DuL = 
[[ 5.  3.  1.]
 [ 6.  2.  1.]
 [ 4.  1.  1.]
 [ 8.  5. -1.]
 [ 2.  4. -1.]
 [ 3.  6. -1.]
 [ 7.  6. -1.]]


## 22 訓練事例数

`DuL`から訓練事例数$\mid D_{u}^{L} \mid$を取得するコードを書きなさい。

In [23]:
print('|DuL| = {}'.format(DuL.shape[0]))

|DuL| = 7


## 23 正事例数

`DuL`から正事例数$\mid D_{u}^{L+} \mid$を取得するコードを書きなさい。

In [30]:
# print('|DuL+| = {}'.format(DuL[DuL[:, -1] == +1].shape[0]))
print('|DuL+| = {}'.format(DuL[ru[Iu]==+1].shape[0]))

|DuL+| = 3


## 24 負事例数

DuLから負事例数$$\mid D_{u}^{L-} \mid$$を取得するコードを書きなさい。

In [28]:
# print('|DuL-| = {}'.format(DuL[DuL[:, -1] == -1].shape[0]))
print('|DuL-| = {}'.format(DuL[ru[Iu]==-1].shape[0]))

|DuL-| = 4


## 25 予測対象データ

`Du`から予測対象データ$D^{U}_{u}$を`ndarray`として生成するコードを書きなさい。得られた`ndarray`を`DuU`とすること。

In [26]:
DuU = Du[Iu_not]

print('DuU = \n{}'.format(DuU))

DuU = 
[[ 4.  2. nan]
 [ 5.  1. nan]
 [ 8.  6. nan]
 [ 3.  4. nan]
 [ 4.  7. nan]
 [ 4.  4. nan]]


## 26 予測対象事例数

`DuU`から予測対象事例数$\mid D_{u}^{U} \mid$を取得するコードを書きなさい。

In [27]:
print('|DuU| = {}'.format(DuU.shape[0]))

|DuU| = 6
